name: deeprig
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.19,<1.20
  - pandas>=1.3,<1.4
  - tensorflow>=2.4.0,<2.5.0
  - tensorflow-gpu>=2.4.0,<2.5.0
  - scipy>=1.7,<1.8
  - scanpy>=1.7,<1.8
  - networkx>=2.5,<2.6
  - scikit-learn>=1.0,<1.1
  - protobuf >= 3.20, <3.21